# API наценки
[[redirects]]
  from = "/markupApi/*"
  to = "https://api-markup-service.onrender.com""
  status = 200
  force = true

# API покупки
[[redirects]]
  from = "/purchaseApi/*"
  to = "https://api-purchase-service.onrender.com"
  status = 200
  force = true

# API продаж
[[redirects]]
  from = "/salesApi/*"
  to = "https://api-info-sales.onrender.com"
  status = 200
  force = true

# API анализа
[[redirects]]
  from = "/analysisApi/*"
  to = "https://api-analysis-data.onrender.com""
  status = 200
  force = true
